import { z } from 'zod';
import {
  StructuredCVSchema,
  StructuredJobDescriptionSchema,
} from '../../schemas/StructuredInputs.js';

/** Reusable detail shape for a section: summary + bullets. Relaxed min lengths for assessment/interview output to reduce validation failures. */
export const SectionDetailSchema = z.object({
  section_detail_summary: z
    .string()
    .min(120)
    .describe('Plain-text content summary of the section.'),
  summary_detail_bullets: z
    .array(
      z.string().min(60).describe('Single bullet for the section.')
    )
    .min(1)
    .describe('Bullet list for the section (at least one bullet).'),
});

export const SectionSchema = z
  .object({
    section_heading: z
      .string()
      .min(1)
      .describe(
        'Section title. May be given in the prompt or generated by the model.'
      ),
    section_description: z
      .string()
      .min(1)
      .describe(
        'Description of the section. May be given in the prompt or generated by the model.'
      ),
    section_detail: SectionDetailSchema,
  })
  .describe(
    'Single section containing a heading, description, and details. Section must be derived from the prompt. For all string values in this shape: do not pad with newlines or repeated spaces to reach max length; use substantive content only.'
  );

/** Section type enum for assessment output. All eight must appear exactly once in sections. */
export const AssessmentSectionTypeEnum = z.enum([
  'narrative',
  'strengths',
  'concerns',
  'recommendations',
  'interview_questions',
  'missing_signals',
  'interview_risks',
  'reasons_to_hire',
  'reasons_not_to_hire',
]);

const REQUIRED_ASSESSMENT_SECTION_TYPES = [
  'narrative',
  'strengths',
  'concerns',
  'recommendations',
  'interview_questions',
  'missing_signals',
  'interview_risks',
  'reasons_to_hire',
  'reasons_not_to_hire',
] as const;

/** Assessment section: Section with a type discriminator. */
export const AssessmentSectionSchema = SectionSchema.extend({
  type: AssessmentSectionTypeEnum,
}).strict();

export { StructuredCVSchema, StructuredJobDescriptionSchema };

// -----------------------------------------------------------------------------
// Shared primitives (single source of truth for consistency)
// -----------------------------------------------------------------------------

/** Score or confidence in 0-100 range. Use for all single score/confidence fields. */
export const Score0To100Schema = z.number().min(0).max(100);

/** Hire/declined/maybe decision. Use for decision and final_decision fields. */
export const DecisionEnumSchema = z.enum(['hire', 'declined', 'maybe']);

/** Array of strings, default empty. Use for strengths, concerns, recommendations, next_steps, signal_gaps, etc. */
export const StringArraySchema = z.array(z.string()).default([]);

/** Skill representation mode for CV/seniority outputs. */
export const SkillRepresentationModeSchema = z.enum(['keywords', 'narrative']);

export const ExperienceFormatSchema = z.enum(['bullets', 'hybrid', 'narrative']);

export const SeniorityLevelSchema = z.enum(['bullets', 'narrative']);

/** Industry-agnostic seniority class used for deterministic representation policy. */
export const SeniorityClassSchema = z.enum([
  'entry',
  'intermediate',
  'senior',
  'lead',
  'manager',
  'head',
  'executive',
  'unknown',
]);

/** Primary career track for the target or candidate profile. */
export const SeniorityTrackSchema = z.enum([
  'individual_contributor',
  'people_manager',
  'hybrid',
]);

/** Scope of ownership independent of title semantics. */
export const ScopeLevelSchema = z.enum([
  'task',
  'project',
  'team',
  'multi_team',
  'function',
  'org',
]);

/** Decision and impact time horizon for the role context. */
export const ImpactHorizonSchema = z.enum([
  'short_term',
  'annual',
  'multi_year',
]);

/** Degree of ambiguity handled by the role or candidate evidence. */
export const AmbiguityLevelSchema = z.enum([
  'low',
  'medium',
  'high',
]);

// -----------------------------------------------------------------------------
// Signal dimension keys (two naming conventions; API and merge logic depend on these exact names)
// - Aggregated: stage_4 signal_normalized, stage_5 calibration, listFields, stage_14 signalBlocks
// - Signal blocks: common (assessment/consensus narrative signal_blocks)
// -----------------------------------------------------------------------------

export const SIGNAL_AGGREGATED_KEYS = [
  'technical_scope',
  'execution_authority',
  'leadership_impact',
  'delivery_risk',
  'business_alignment',
] as const;

export const SIGNAL_BLOCKS_KEYS = [
  'technical_depth',
  'execution_maturity',
  'leadership_scope',
  'delivery_risk',
  'business_alignment',
] as const;

/** Five-category optional scores (0-100 each). Used by stage_4 confidence_scores and stage_5 calibrated_scores. */
export const SignalCategoryScoresSchema = z
  .object({
    technical_scope: Score0To100Schema.optional(),
    execution_authority: Score0To100Schema.optional(),
    leadership_impact: Score0To100Schema.optional(),
    business_alignment: Score0To100Schema.optional(),
    delivery_risk: Score0To100Schema.optional(),
  })
  .default({});

/** Five-category string arrays (aggregated signals). Used by stage_4 aggregated_signals. */
export const SignalCategoryArraysSchema = z.object({
  technical_scope: StringArraySchema,
  execution_authority: StringArraySchema,
  leadership_impact: StringArraySchema,
  delivery_risk: StringArraySchema,
  business_alignment: StringArraySchema,
});

// CandidateProfile - matches Pydantic CandidateProfile (input schema)
export const CandidateProfileSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
  company_name: z.string().min(1),
  role_applying_for: z.string().min(1),
  structured_cv: StructuredCVSchema,
  structured_job_description: StructuredJobDescriptionSchema,
  criticality_level: z.enum(['critical', 'thorough', 'objective', 'lenient', 'harsh', 'easygoing', 'constructive']).default('objective'),
  verbosity_level: z.enum(['concise', 'moderate', 'detailed']).default('moderate'),
  cv_optimization_level: z.enum(['conservative', 'moderate', 'aggressive']).default('moderate'),
  audience_perspective: z.enum(['candidate', 'hiring_organisation']).default('candidate'),
  job_posted_by_recruiter: z.boolean().default(false),
  is_rerun_with_updated_cv: z.boolean().optional(),
  cv_optimization_rerun_count: z.number().int().min(0).optional(),
  previous_run_scores: z.record(z.string(), z.number()).optional(),
  previous_optimization_did_not_improve_scores: z.boolean().optional(),
  previous_final_decision: DecisionEnumSchema.optional(),
  previous_final_confidence: z.number().int().min(0).max(100).optional(),
  selected_missing_skills: z.array(z.string()).optional(),
  previous_optimized_cv: z.unknown().optional(),
  previous_optimized_cv_hash: z.string().optional(),
  org_scope_metadata: z.record(z.string(), z.unknown()).optional(),
});

export const InterviewQuestionSchema = z.object({
  id: z.string(),
  text: z.string(),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  focus_area: z.string(),
});

/** Count easy / medium / hard (only these enum values should appear). */
export function countInterviewQuestionDifficulties(questions: { difficulty: string }[]): {
  easy: number;
  medium: number;
  hard: number;
  total: number;
} {
  let easy = 0;
  let medium = 0;
  let hard = 0;
  for (const q of questions) {
    if (q.difficulty === 'easy') easy += 1;
    else if (q.difficulty === 'medium') medium += 1;
    else if (q.difficulty === 'hard') hard += 1;
  }
  return { easy, medium, hard, total: questions.length };
}

/**
 * True when n >= 10 and each difficulty count is in [floor(n/3), ceil(n/3)]
 * (as even a split as possible, e.g. n=10 -> 4+3+3 in any order).
 */
export function hasBalancedInterviewDifficulties(
  easy: number,
  medium: number,
  hard: number,
  total: number
): boolean {
  if (total < 10) return false;
  if (easy + medium + hard !== total) return false;
  const low = Math.floor(total / 3);
  const high = Math.ceil(total / 3);
  return (
    easy >= low &&
    easy <= high &&
    medium >= low &&
    medium <= high &&
    hard >= low &&
    hard <= high
  );
}

export const INTERVIEW_QUESTIONS_BALANCE_REFINE_MESSAGE =
  'interview_questions must have at least 10 items and difficulties balanced: with n = length, each of easy, medium, hard must appear between floor(n/3) and ceil(n/3) times (e.g. n=10: exactly 4, 3, and 3 in some order)';

const RichTextParagraphBlockSchema = z.object({
  type: z.literal('paragraph'),
  text: z.string().min(1),
});

const RichTextListBlockSchema = z.object({
  type: z.literal('list'),
  ordered: z.boolean(),
  items: z.array(z.string().min(1)).min(1),
});

const RichTextBlockSchema = z.union([RichTextParagraphBlockSchema, RichTextListBlockSchema]);
export const RichTextContentSchema = z.union([z.string().min(1), z.array(RichTextBlockSchema).min(2)]);

/** Block shape: summary and description are RichTextContent (string or array of RichTextBlock) for backward compatibility and rich long-form content. */
export const HeadingSummarySchema = z.object({
  heading: z.string().min(1),
  description: RichTextContentSchema,
  contextual_help: z.string().min(1),
});

export type RichTextBlock = z.infer<typeof RichTextBlockSchema>;
export type RichTextContent = z.infer<typeof RichTextContentSchema>;

/** Signal blocks use SIGNAL_BLOCKS_KEYS; same five dimensions as aggregated but different property names (used in assessment/consensus). */
const SignalBlocksSchema = z
  .object({
    technical_depth: StringArraySchema,
    execution_maturity: StringArraySchema,
    leadership_scope: StringArraySchema,
    delivery_risk: StringArraySchema,
    business_alignment: StringArraySchema,
  })
  .optional();

/** Refine message for section-type coverage. Exported for use in consensus schema. */
export const ASSESSMENT_SECTIONS_REFINE_MESSAGE = `sections must contain exactly one section of each type: ${REQUIRED_ASSESSMENT_SECTION_TYPES.join(', ')}`;

/** Refine predicate: sections must contain exactly one section per assessment type. Exported for consensus schema. */
export function requireAllAssessmentSectionTypes(data: { sections: { type: string }[] }): boolean {
  const types = new Set(data.sections.map((s) => s.type));
  return (
    types.size === REQUIRED_ASSESSMENT_SECTION_TYPES.length &&
    REQUIRED_ASSESSMENT_SECTION_TYPES.every((t) => types.has(t))
  );
}

/** Base assessment shape without refine; use this when extending (e.g. consensus). */
export const AssessmentResultBaseObjectSchema = z.object({
  decision: DecisionEnumSchema,
  score: Score0To100Schema,
  signal_blocks: SignalBlocksSchema,
  demonstrated_strengths: StringArraySchema.optional(),
  declared_skills_to_validate: StringArraySchema.optional(),
  final_decision: DecisionEnumSchema.optional(),
  confidence: Score0To100Schema.optional(),
  sections: z.array(AssessmentSectionSchema),
});

export const AssessmentResultBaseSchema = AssessmentResultBaseObjectSchema.refine(
  requireAllAssessmentSectionTypes,
  { message: ASSESSMENT_SECTIONS_REFINE_MESSAGE }
);

/** Interview agents (stage_3): assessment shape plus structured sample questions with balanced difficulty. */
export const InterviewAssessmentSchema = AssessmentResultBaseObjectSchema.extend({
  interview_questions: z
    .array(InterviewQuestionSchema)
    .min(10)
    .describe(
      'At least 10 interview questions. Spread easy, medium, and hard as evenly as possible (for n items, each difficulty count must be floor(n/3) or ceil(n/3)).'
    ),
}).refine(
  (data) => {
    const qs = data.interview_questions;
    const { easy, medium, hard, total } = countInterviewQuestionDifficulties(qs);
    return hasBalancedInterviewDifficulties(easy, medium, hard, total);
  },
  { message: INTERVIEW_QUESTIONS_BALANCE_REFINE_MESSAGE, path: ['interview_questions'] }
);

export const AssessmentResultSchema = AssessmentResultBaseSchema;

export const RecruitmentDecisionOutputSchema = AssessmentResultSchema;

export function normalizeAssessmentScore(score: number): { score: number; corrected: boolean } {
  if (typeof score !== 'number' || Number.isNaN(score)) return { score, corrected: false };
  if (score >= 0 && score <= 10) {
    return { score: Math.round(score * 10), corrected: true };
  }
  return { score, corrected: false };
}

export type SectionDetail = z.infer<typeof SectionDetailSchema>;
export type AssessmentSection = z.infer<typeof AssessmentSectionSchema>;
export type HeadingSummary = z.infer<typeof HeadingSummarySchema>;
export type CandidateProfile = z.infer<typeof CandidateProfileSchema>;
export type InterviewQuestion = z.infer<typeof InterviewQuestionSchema>;
export type AssessmentResult = z.infer<typeof AssessmentResultSchema>;
export type InterviewAssessmentResult = z.infer<typeof InterviewAssessmentSchema>;
export type RecruitmentDecisionOutput = z.infer<typeof RecruitmentDecisionOutputSchema>;
